gnip:
  account_name: MyGnipAccountName
  user_name: me@there.com
  password: N0TMYp455w0rD
  label: prod
  product: pt #pt, fas, 30day

#output: stdout #Either write to stdout or write to db. (option coming?)

logging:
  log_level: debug  #The standard debug, info, error, warn or fatal.
  log_file: ./pt-stream-pi.log
